import { NextResponse } from "next/server";
import { resend } from "@/lib/email";

export async function POST(req: Request) {
  try {
    const { email, results } = await req.json();

    if (!email || !results) {
      return NextResponse.json({ error: "Missing required parameters" }, { status: 400 });
    }

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <style>
            body { font-family: Arial, sans-serif; color: #333; line-height: 1.6; padding: 20px; }
            .header { text-align: center; border-bottom: 2px solid #3b82f6; padding-bottom: 15px; margin-bottom: 25px; }
            .hero-score { font-size: 32px; font-weight: bold; color: #3b82f6; }
            .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 15px; margin-bottom: 20px; }
            .table { width: 100%; border-collapse: collapse; margin-top: 10px; }
            .table th, .table td { border: 1px solid #cbd5e1; padding: 8px 12px; text-align: left; font-size: 13px; }
            .table th { background: #f1f5f9; }
            .badge-success { background: #dcfce7; color: #166534; padding: 3px 8px; border-radius: 999px; font-size: 11px; font-weight: bold; }
            .badge-error { background: #fee2e2; color: #991b1b; padding: 3px 8px; border-radius: 999px; font-size: 11px; font-weight: bold; }
          </style>
        </head>
        <body>
          <div class="header">
            <h2>IELTS Academic Listening Report</h2>
            <p>AI-IELTS Official Assessment Summary</p>
          </div>

          <div class="card" style="text-align: center;">
            <div>Overall Band Score</div>
            <div class="hero-score">${results.bandScore.toFixed(1)}</div>
            <div>Raw Score: <strong>${results.score} / 40</strong> (${results.accuracy.toFixed(0)}% Accuracy)</div>
          </div>

          <div class="card">
            <h3>Section Breakdown</h3>
            <table class="table">
              <thead>
                <tr>
                  <th>Section</th>
                  <th>Difficulty</th>
                  <th>Score</th>
                  <th>Accuracy</th>
                </tr>
              </thead>
              <tbody>
                ${(results.sectionScores || [])
                  .map(
                    (s: any) => {
                      const pct = s.percentage ?? (s.total > 0 ? (s.correct / s.total) * 100 : 0);
                      const diff = (s.difficulty || "mixed").toUpperCase();
                      return `
                  <tr>
                    <td>Section ${(s.sectionIndex ?? 0) + 1}</td>
                    <td>${diff}</td>
                    <td>${s.correct ?? 0} / ${s.total ?? 10}</td>
                    <td>${pct.toFixed(0)}%</td>
                  </tr>
                `;
                    }
                  )
                  .join("")}
              </tbody>
            </table>
          </div>

          <div class="card">
            <h3>Recommendations</h3>
            <ul>
              ${results.recommendations.map((r: string) => `<li>${r}</li>`).join("")}
            </ul>
          </div>

          <div style="text-align: center; color: #64748b; font-size: 12px; margin-top: 30px;">
            Generated by AI-IELTS • Practice makes perfect
          </div>
        </body>
      </html>
    `;

    const data = await resend.emails.send({
      from: "AI IELTS <onboarding@resend.dev>",
      to: email,
      subject: `Your IELTS Listening Test Report (Band ${results.bandScore.toFixed(1)})`,
      html: htmlContent,
    });

    return NextResponse.json({ success: true, data });
  } catch (err: any) {
    console.error("Error sending email:", err);
    return NextResponse.json({ error: err.message || "Failed to send email" }, { status: 500 });
  }
}
