// import { db } from "@/lib/db";

// async function main() {
//   console.log("🌱 Seeding database...");

//   // Example: Create a test user
//   const user = await db.user.upsert({
//     where: { email: "admin@example.com" },
//     update: {},
//     create: {
//       id: "admin-user-id",
//       email: "admin@example.com",
//       name: "Admin User",
//       emailVerified: true,
//       role: "admin",
//       createdAt: new Date(),
//       updatedAt: new Date(),
//     },
//   });

//   console.log(`✅ Created user: ${user.email}`);
//   console.log("🌳 Seeding complete.");
// }

// main()
//   .catch((e) => {
//     console.error(e);
//     process.exit(1);
//   })
//   .finally(async () => {
//     // No need to disconnect manually if using the adapter-pg pool correctly, 
//     // but good practice if you had a direct client.
//   });







import { db } from "@/lib/db";

async function main() {
  console.log("🌱 Seeding database...");

  // ── Existing User Seed ──────────────────────
  const user = await db.user.upsert({
    where: { email: "admin@example.com" },
    update: {},
    create: {
      id: "admin-user-id",
      email: "admin@example.com",
      name: "Admin User",
      emailVerified: true,
      role: "admin",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  });
  console.log(`✅ Created user: ${user.email}`);

  // ── Writing Task 1 Images ───────────────────
  console.log("📊 Seeding Writing Task 1 images...");

  const task1Images = [
    // ── BAR CHARTS ──
    {
      id: "bar_001",
      chartType: "bar_chart",
      imageUrl: "https://www.ielts-mentor.com/images/writingimage8/ielts-writing-task-1-bar-graph-uk-school-budget.png",
      title: "UK School Budget Expenditure 2000-2010",
      difficulty: "medium",
      dataPoints: JSON.stringify({
        description: "Bar chart showing UK school budget spent on different categories from 2000 to 2010",
        data: {
          "Teachers' salaries": { "2000": "40%", "2005": "45%", "2010": "50%" },
          "Furniture & equipment": { "2000": "15%", "2005": "18%", "2010": "20%" },
          "Insurance": { "2000": "8%", "2005": "7%", "2010": "6%" },
          "Other workers' salaries": { "2000": "22%", "2005": "20%", "2010": "15%" },
          "Resources (books etc)": { "2000": "15%", "2005": "10%", "2010": "9%" },
        },
        trend: "Teachers salaries increased significantly while other costs decreased",
        years: ["2000", "2005", "2010"],
      }),
    },
    {
      id: "bar_002",
      chartType: "bar_chart",
      imageUrl: "https://www.ielts-mentor.com/images/writingimage8/ielts-writing-task-1-bar-chart-age-of-people-going-abroad.png",
      title: "Percentage of People Travelling Abroad by Age Group",
      difficulty: "easy",
      dataPoints: JSON.stringify({
        description: "Bar chart showing percentage of people from different age groups who travelled abroad in a given year",
        data: {
          "Under 25": "30%",
          "25-34": "42%",
          "35-44": "38%",
          "45-54": "25%",
          "55-64": "18%",
          "65+": "10%",
        },
        trend: "People aged 25-34 travelled abroad the most, with older groups travelling less",
        unit: "percentage of population",
      }),
    },
    {
      id: "bar_003",
      chartType: "bar_chart",
      imageUrl: "https://www.ielts-mentor.com/images/writingimage8/ielts-bar-chart-electricity-generated-by-different-sources.png",
      title: "Electricity Generated by Different Sources 1980-2010",
      difficulty: "hard",
      dataPoints: JSON.stringify({
        description: "Bar chart showing electricity generation in TWh from different energy sources",
        data: {
          "Coal": { "1980": "200", "1990": "220", "2000": "180", "2010": "140" },
          "Natural Gas": { "1980": "80", "1990": "120", "2000": "160", "2010": "200" },
          "Nuclear": { "1980": "60", "1990": "100", "2000": "120", "2010": "130" },
          "Renewable": { "1980": "10", "1990": "20", "2000": "50", "2010": "110" },
        },
        unit: "TWh",
        trend: "Coal declined while natural gas and renewables increased significantly",
        years: ["1980", "1990", "2000", "2010"],
      }),
    },

    // ── LINE GRAPHS ──
    {
      id: "line_001",
      chartType: "line_graph",
      imageUrl: "https://www.ielts-mentor.com/images/writingimage8/ielts-line-graph-average-house-prices.png",
      title: "Average House Prices in UK Cities 1990-2010",
      difficulty: "medium",
      dataPoints: JSON.stringify({
        description: "Line graph showing average house prices in thousands of pounds in four UK cities",
        data: {
          "London": { "1990": 120, "1995": 140, "2000": 200, "2005": 280, "2010": 350 },
          "Birmingham": { "1990": 60, "1995": 70, "2000": 90, "2005": 110, "2010": 130 },
          "Manchester": { "1990": 55, "1995": 65, "2000": 85, "2005": 100, "2010": 120 },
          "Leeds": { "1990": 50, "1995": 58, "2000": 75, "2005": 90, "2010": 105 },
        },
        unit: "thousands of pounds (£)",
        trend: "London prices rose dramatically, far outpacing other cities",
        years: ["1990", "1995", "2000", "2005", "2010"],
      }),
    },
    {
      id: "line_002",
      chartType: "line_graph",
      imageUrl: "https://www.ielts-mentor.com/images/writingimage8/ielts-line-graph-goods-transport.png",
      title: "Goods Transport in UK by Method 1974-2002",
      difficulty: "medium",
      dataPoints: JSON.stringify({
        description: "Line graph showing billion tonne/km of goods transported by different methods in the UK",
        data: {
          "Road": { "1974": 70, "1982": 80, "1990": 100, "1998": 120, "2002": 130 },
          "Water": { "1974": 40, "1982": 42, "1990": 58, "1998": 65, "2002": 70 },
          "Rail": { "1974": 40, "1982": 30, "1990": 35, "1998": 38, "2002": 40 },
          "Pipeline": { "1974": 5, "1982": 15, "1990": 20, "1998": 22, "2002": 20 },
        },
        unit: "billion tonne/km",
        trend: "Road transport increased consistently and remained the dominant method",
      }),
    },

    // ── PIE CHARTS ──
    {
      id: "pie_001",
      chartType: "pie_chart",
      imageUrl: "https://www.ielts-mentor.com/images/writingimage8/ielts-pie-chart-household-expenditure.png",
      title: "Household Expenditure in Australia and New Zealand",
      difficulty: "easy",
      dataPoints: JSON.stringify({
        description: "Two pie charts comparing household expenditure categories in Australia and New Zealand",
        data: {
          "Australia": {
            "Food & Drink": "22%",
            "Housing": "28%",
            "Transport": "15%",
            "Healthcare": "12%",
            "Entertainment": "10%",
            "Other": "13%",
          },
          "New Zealand": {
            "Food & Drink": "27%",
            "Housing": "25%",
            "Transport": "12%",
            "Healthcare": "10%",
            "Entertainment": "13%",
            "Other": "13%",
          },
        },
        trend: "Housing was largest in Australia; Food was largest in New Zealand",
      }),
    },
    {
      id: "pie_002",
      chartType: "pie_chart",
      imageUrl: "https://www.ielts-mentor.com/images/writingimage8/ielts-pie-chart-energy-use.png",
      title: "Energy Use in an Average Australian Home",
      difficulty: "easy",
      dataPoints: JSON.stringify({
        description: "Pie chart showing the percentage of total energy used for different purposes in an average Australian home",
        data: {
          "Heating": "42%",
          "Water Heating": "30%",
          "Refrigeration": "7%",
          "Lighting": "4%",
          "Cooling": "2%",
          "Other Appliances": "15%",
        },
        trend: "Heating dominates energy use, followed by water heating",
      }),
    },

    // ── TABLES ──
    {
      id: "table_001",
      chartType: "table",
      imageUrl: "https://www.ielts-mentor.com/images/writingimage8/ielts-table-population-of-four-countries.png",
      title: "Population Statistics for Four Countries",
      difficulty: "medium",
      dataPoints: JSON.stringify({
        description: "Table showing population, growth rate, and urban population percentage for four countries",
        data: {
          "China": { "Population (millions)": 1384, "Growth Rate": "0.4%", "Urban Population": "57%" },
          "India": { "Population (millions)": 1296, "Growth Rate": "1.1%", "Urban Population": "33%" },
          "USA": { "Population (millions)": 326, "Growth Rate": "0.7%", "Urban Population": "82%" },
          "Australia": { "Population (millions)": 25, "Growth Rate": "1.4%", "Urban Population": "89%" },
        },
        trend: "Australia has highest urbanization; India has highest growth rate",
        year: "2018",
      }),
    },
    {
      id: "table_002",
      chartType: "table",
      imageUrl: "https://www.ielts-mentor.com/images/writingimage8/ielts-table-changes-in-working-patterns.png",
      title: "Changes in Working Patterns 1992-2002",
      difficulty: "hard",
      dataPoints: JSON.stringify({
        description: "Table showing percentage of men and women in different working patterns in the UK",
        data: {
          "Full-time (Men)": { "1992": "71%", "1997": "69%", "2002": "67%" },
          "Full-time (Women)": { "1992": "36%", "1997": "38%", "2002": "40%" },
          "Part-time (Men)": { "1992": "6%", "1997": "7%", "2002": "9%" },
          "Part-time (Women)": { "1992": "42%", "1997": "43%", "2002": "44%" },
        },
        trend: "Women increasingly working full-time; men increasingly working part-time",
      }),
    },

    // ── PROCESS DIAGRAMS ──
    {
      id: "process_001",
      chartType: "process_diagram",
      imageUrl: "https://www.ielts-mentor.com/images/writingimage8/ielts-process-diagram-water-cycle.png",
      title: "The Water Cycle",
      difficulty: "medium",
      dataPoints: JSON.stringify({
        description: "Process diagram showing the natural water cycle",
        stages: [
          "Solar energy heats surface water in oceans, lakes, and rivers",
          "Water evaporates and rises as water vapour",
          "Water vapour condenses to form clouds",
          "Precipitation falls as rain or snow",
          "Surface runoff flows into rivers and streams",
          "Water seeps into ground (groundwater)",
          "Rivers carry water back to oceans",
          "Cycle repeats",
        ],
        keyTerms: ["evaporation", "condensation", "precipitation", "runoff", "groundwater"],
      }),
    },
    {
      id: "process_002",
      chartType: "process_diagram",
      imageUrl: "https://www.ielts-mentor.com/images/writingimage8/ielts-process-diagram-glass-recycling.png",
      title: "How Glass is Recycled",
      difficulty: "easy",
      dataPoints: JSON.stringify({
        description: "Process diagram showing the glass recycling process",
        stages: [
          "Glass collected from households and businesses",
          "Glass transported to recycling centre",
          "Glass sorted by colour (clear, green, brown)",
          "Contaminants removed (labels, caps)",
          "Glass crushed into cullet",
          "Cullet melted in furnace at 1500°C",
          "Molten glass moulded into new products",
          "New glass products distributed",
        ],
        keyTerms: ["cullet", "furnace", "sorted", "contaminants", "moulded"],
      }),
    },

    // ── MAPS ──
    {
      id: "map_001",
      chartType: "map",
      imageUrl: "https://www.ielts-mentor.com/images/writingimage8/ielts-map-town-development.png",
      title: "Development of a Town 1970-2010",
      difficulty: "hard",
      dataPoints: JSON.stringify({
        description: "Two maps showing changes to a town between 1970 and 2010",
        changes: {
          "1970": "Small town with farmland to north, river to south, single road through centre",
          "2010": "Expanded with new housing estate in north (farmland removed), shopping centre in east, bridge over river, ring road added",
        },
        keyChanges: [
          "Farmland replaced by housing estate",
          "New shopping centre built in east",
          "Bridge constructed over river",
          "Ring road built around town",
          "Town population doubled",
        ],
        trend: "Significant urban expansion with infrastructure development",
      }),
    },
  ];

  // Upsert all images
  for (const image of task1Images) {
    await db.writingTask1Image.upsert({
      where: { id: image.id },
      update: {
        imageUrl: image.imageUrl,
        title: image.title,
        dataPoints: image.dataPoints,
        difficulty: image.difficulty,
      },
      create: image,
    });
    console.log(`✅ Seeded: ${image.chartType} — ${image.title}`);
  }

  console.log(`\n📊 Total images seeded: ${task1Images.length}`);
  console.log("🌳 Seeding complete.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {});