# # agents/question_agent.py
# # IELTS Question Generator Agent
# # LLM generates random authentic IELTS questions on every call

# import json
# import re
# import random
# from loguru import logger

# from langchain_groq import ChatGroq
# from langchain_core.messages import HumanMessage, SystemMessage

# from core.config import settings
# from tools.question_generator import (
#     TASK2_ESSAY_TYPES,
#     TASK2_TOPICS,
#     TASK1_CHART_TYPES,
#     TASK1_ACADEMIC_TOPICS,
#     TASK2_GENERATION_PROMPT,
#     TASK1_GENERATION_PROMPT,
# )
# from schemas.question_schema import (
#     GeneratedTask1Question,
#     GeneratedTask2Question,
#     GeneratedWritingQuestions,
#     TestType,
# )


# QUESTION_SYSTEM_PROMPT = """You are an official IELTS question writer trained by the British Council.
# You generate authentic, exam-ready IELTS Writing questions.
# You ALWAYS return valid JSON only. No preamble, no explanation, no markdown."""


# class QuestionGeneratorAgent:
#     """
#     Generates random IELTS Writing questions using LLM.
#     Each call produces a unique, authentic question set.
#     """

#     def __init__(self):
#         self.llm = ChatGroq(
#             model=settings.LLM_MODEL,
#             groq_api_key=settings.GROQ_API_KEY,
#             max_tokens=1024,
#             temperature=0.9,  # High temp = more variety
#         )
#         logger.info("QuestionGeneratorAgent initialized")

#     async def generate_questions(
#         self,
#         test_type: TestType,
#     ) -> GeneratedWritingQuestions:
#         """
#         Generate Task 1 + Task 2 questions for a test session.
#         Both questions are randomly generated by LLM.
#         """
#         logger.info(f"Generating questions — Type: {test_type}")

#         # Generate both in parallel would be ideal, doing sequentially for simplicity
#         task2 = await self._generate_task2()

#         if test_type == TestType.ACADEMIC:
#             task1 = await self._generate_task1_academic()
#         else:
#             task1 = await self._generate_task1_general()

#         return GeneratedWritingQuestions(
#             test_type=test_type,
#             task1=task1,
#             task2=task2,
#         )

#     # ─────────────────────────────────────────
#     # TASK 2 — Essay Question Generator
#     # ─────────────────────────────────────────

#     async def _generate_task2(self) -> GeneratedTask2Question:
#         # Random essay type and topic
#         essay_type = random.choice(TASK2_ESSAY_TYPES)
#         topic = random.choice(TASK2_TOPICS)

#         logger.info(f"Generating Task 2 — Type: {essay_type} | Topic: {topic}")

#         prompt = TASK2_GENERATION_PROMPT.format(
#             essay_type=essay_type,
#             topic=topic,
#         )

#         response = await self._call_llm(prompt)
#         data = self._parse_json(response)

#         return GeneratedTask2Question(
#             id=f"t2_{essay_type}_{random.randint(1000, 9999)}",
#             essay_type=data.get("essay_type", essay_type),
#             prompt_text=data["prompt_text"],
#         )

#     # ─────────────────────────────────────────
#     # TASK 1 ACADEMIC — Chart/Graph Generator
#     # ─────────────────────────────────────────

#     async def _generate_task1_academic(self) -> GeneratedTask1Question:
#         chart_type = random.choice(TASK1_CHART_TYPES)
#         topic = random.choice(TASK1_ACADEMIC_TOPICS)

#         logger.info(f"Generating Task 1 Academic — Chart: {chart_type} | Topic: {topic}")

#         prompt = TASK1_GENERATION_PROMPT.format(
#             chart_type=chart_type,
#             topic=topic,
#         )

#         response = await self._call_llm(prompt)
#         data = self._parse_json(response)

#         # For academic: image_url will come from DB based on chart_type
#         # For now we use a placeholder — DB integration next step
#         image_url = self._get_chart_image(chart_type)

#         return GeneratedTask1Question(
#             id=f"t1_{chart_type}_{random.randint(1000, 9999)}",
#             chart_type=data.get("chart_type", chart_type),
#             prompt_text=data["prompt_text"],
#             description=data["description"],
#             image_url=image_url,
#             test_type="academic",
#         )

#     # ─────────────────────────────────────────
#     # TASK 1 GENERAL — Letter Generator
#     # ─────────────────────────────────────────

#     async def _generate_task1_general(self) -> GeneratedTask1Question:
#         logger.info("Generating Task 1 General Training — Letter")

#         prompt = """You are an official IELTS question writer.
# Generate ONE authentic IELTS General Training Writing Task 1 letter question.

# RULES:
# - Must be a realistic situation requiring a letter
# - Must include exactly 3 bullet points the student must cover
# - Letter type must be one of: formal, semi-formal, informal
# - Match real IELTS past paper style

# Return ONLY this JSON:
# {
#   "letter_type": "formal|semi-formal|informal",
#   "prompt_text": "<full situation description + 3 bullet points>",
#   "description": "<brief summary of what letter to write>"
# }"""

#         response = await self._call_llm(prompt)
#         data = self._parse_json(response)

#         return GeneratedTask1Question(
#             id=f"t1_letter_{random.randint(1000, 9999)}",
#             chart_type="letter",
#             prompt_text=data["prompt_text"],
#             description=data.get("description", ""),
#             image_url="",
#             test_type="general",
#         )

#     # ─────────────────────────────────────────
#     # LLM CALL
#     # ─────────────────────────────────────────

#     async def _call_llm(self, user_prompt: str) -> str:
#         messages = [
#             SystemMessage(content=QUESTION_SYSTEM_PROMPT),
#             HumanMessage(content=user_prompt),
#         ]
#         response = await self.llm.ainvoke(messages)
#         return response.content

#     def _parse_json(self, response: str) -> dict:
#         clean = re.sub(r'```(?:json)?\n?', '', response).strip().rstrip('`')
#         return json.loads(clean)

#     def _get_chart_image(self, chart_type: str) -> str:
#         """
#         Returns image URL from DB based on chart type.
#         TODO: Replace with actual DB query when images are seeded.
#         Using placeholder IELTS sample images for now.
#         """
#         placeholders = {
#             "bar_chart":       "https://www.ielts-mentor.com/images/readingimage/bar-graph.jpg",
#             "line_graph":      "https://www.ielts-mentor.com/images/readingimage/line-graph.jpg",
#             "pie_chart":       "https://www.ielts-mentor.com/images/readingimage/pie-chart.jpg",
#             "table":           "https://www.ielts-mentor.com/images/readingimage/table.jpg",
#             "process_diagram": "https://www.ielts-mentor.com/images/readingimage/process-diagram.jpg",
#             "map":             "https://www.ielts-mentor.com/images/readingimage/map.jpg",
#         }
#         return placeholders.get(chart_type, placeholders["bar_chart"])








# agents/question_agent.py
# IELTS Question Generator Agent

import json
import re
import random
import httpx
from loguru import logger

from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage

from core.config import settings
from tools.question_generator import (
    TASK2_ESSAY_TYPES,
    TASK2_TOPICS,
    TASK1_CHART_TYPES,
    TASK1_ACADEMIC_TOPICS,
    TASK2_GENERATION_PROMPT,
    TASK1_GENERATION_PROMPT,
)
from schemas.question_schema import (
    GeneratedTask1Question,
    GeneratedTask2Question,
    GeneratedWritingQuestions,
    TestType,
)

QUESTION_SYSTEM_PROMPT = """You are an official IELTS question writer trained by the British Council.
You generate authentic, exam-ready IELTS Writing questions.
You ALWAYS return valid JSON only. No preamble, no explanation, no markdown."""


class QuestionGeneratorAgent:

    def __init__(self):
        self.llm = ChatGroq(
            model=settings.LLM_MODEL,
            groq_api_key=settings.GROQ_API_KEY,
            max_tokens=1024,
            temperature=0.9,
        )
        logger.info("QuestionGeneratorAgent initialized")

    async def generate_questions(self, test_type: TestType) -> GeneratedWritingQuestions:
        logger.info(f"Generating questions — Type: {test_type}")

        task2 = await self._generate_task2()

        if test_type == TestType.ACADEMIC:
            task1 = await self._generate_task1_academic()
        else:
            task1 = await self._generate_task1_general()

        return GeneratedWritingQuestions(
            test_type=test_type,
            task1=task1,
            task2=task2,
        )

    async def _generate_task2(self) -> GeneratedTask2Question:
        essay_type = random.choice(TASK2_ESSAY_TYPES)
        topic = random.choice(TASK2_TOPICS)
        logger.info(f"Generating Task 2 — {essay_type} | {topic}")

        prompt = TASK2_GENERATION_PROMPT.format(essay_type=essay_type, topic=topic)
        response = await self._call_llm(prompt)
        data = self._parse_json(response)

        return GeneratedTask2Question(
            id=f"t2_{essay_type}_{random.randint(1000,9999)}",
            essay_type=data.get("essay_type", essay_type),
            prompt_text=data["prompt_text"],
        )

    async def _generate_task1_academic(self) -> GeneratedTask1Question:
        # Step 1: Pick random chart type
        chart_type = random.choice(TASK1_CHART_TYPES)
        topic = random.choice(TASK1_ACADEMIC_TOPICS)
        logger.info(f"Generating Task 1 Academic — {chart_type} | {topic}")

        # Step 2: Fetch matching image from DB via Next.js API
        image_url, data_points, db_title = await self._fetch_image_from_db(chart_type)

        # Step 3: LLM generates question based on actual chart data
        prompt = TASK1_GENERATION_PROMPT.format(
            chart_type=chart_type,
            topic=db_title or topic,
        )
        response = await self._call_llm(prompt)
        data = self._parse_json(response)

        return GeneratedTask1Question(
            id=f"t1_{chart_type}_{random.randint(1000,9999)}",
            chart_type=data.get("chart_type", chart_type),
            prompt_text=data["prompt_text"],
            description=data_points or data.get("description", ""),
            image_url=image_url,
            test_type="academic",
        )

    async def _generate_task1_general(self) -> GeneratedTask1Question:
        logger.info("Generating Task 1 General — Letter")

        prompt = """You are an official IELTS question writer.
Generate ONE authentic IELTS General Training Writing Task 1 letter question.

RULES:
- Must be a realistic situation requiring a letter
- Must include exactly 3 bullet points the student must cover
- Letter type: formal, semi-formal, or informal
- Match real IELTS past paper style exactly

Return ONLY this JSON:
{
  "letter_type": "formal|semi-formal|informal",
  "prompt_text": "<full situation + 3 bullet points>",
  "description": "<brief summary>"
}"""

        response = await self._call_llm(prompt)
        data = self._parse_json(response)

        return GeneratedTask1Question(
            id=f"t1_letter_{random.randint(1000,9999)}",
            chart_type="letter",
            prompt_text=data["prompt_text"],
            description=data.get("description", ""),
            image_url="",
            test_type="general",
        )

    async def _fetch_image_from_db(self, chart_type: str) -> tuple[str, str, str]:
        """
        Fetch random image from DB via Next.js API route.
        Returns (image_url, data_points, title)
        """
        frontend_url = settings.FRONTEND_URL
        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                res = await client.get(
                    f"{frontend_url}/api/writing/task1-image",
                    params={"chart_type": chart_type}
                )
                if res.status_code == 200:
                    data = res.json()
                    logger.info(f"Fetched image from DB: {data.get('title')}")
                    return (
                        data.get("imageUrl", ""),
                        data.get("dataPoints", ""),
                        data.get("title", ""),
                    )
        except Exception as e:
            logger.warning(f"DB image fetch failed: {e} — using fallback")

        # Fallback if DB call fails
        return ("", "", "")

    async def _call_llm(self, user_prompt: str) -> str:
        messages = [
            SystemMessage(content=QUESTION_SYSTEM_PROMPT),
            HumanMessage(content=user_prompt),
        ]
        response = await self.llm.ainvoke(messages)
        return response.content

    def _parse_json(self, response: str) -> dict:
        clean = re.sub(r'```(?:json)?\n?', '', response).strip().rstrip('`')
        return json.loads(clean)